version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=config.settings
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
    depends_on:
      - chromadb
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: /bin/ollama
    command: serve

  chromadb:
    image: chromadb/chroma:latest
    volumes:
      - chroma_data:/chroma/chroma
      - ./data/processed:/processed_data
    environment:
      - ALLOW_RESET=true
      - CHROMA_SERVER_AUTH_CREDENTIALS_FILE=none
    ports:
      - "8001:8000"

volumes:
  ollama_data:
  chroma_data: